debug: false



info:
  version: '@pom.version@'
  app:
    name: "@pom.name@"
  build:
    version: '@project.version@'
    number:  '@buildNumber@'
    date:    '@maven.build.timestamp@'

ksul:
  archiv:
    server: http://localhost:80/alfresco/
    binding: http://localhost:80/alfresco/api/-default-/public/cmis/versions/1.1/atom
    user: admin
    password: admin
    company-home-name: Firmen-Home
    data-dictionary-name: Datenverzeichnis
    script-directory-name: Skripte


server:
  servlet:
    context-path: /Archiv
  port: 8080

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    info:
      git:
        mode: full

logging:
  path: ./
  level:
    root: info

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  main:
    banner-mode: log
  autoconfigure:
    exclude:
             - org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration
             - org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration