debug: false

info:
  version: '@pom.version@'
  app:
    name: '@pom.name@'
  build:
    version: '@project.version@'
    number:  '@buildNumber@'
    date:    '@maven.build.timestamp@'

ksul:
  archiv:
    server: http://localhost:9080/alfresco/
    binding: http://localhost:9080/alfresco/api/-default-/public/cmis/versions/1.1/atom
    user: admin
    password: admin

server:
  servlet:
    context-path: /Archiv
  port: 8080
  tomcat:
    max-http-post-size: 50000000
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    info:
      git:
        mode: full

logging:
  path: ./
  level:
    root: info

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  main:
    banner-mode: log
