debug: false

info:
  version: '@pom.version@'
  app:
    name: '@pom.name@'
  build:
    version: '@project.version@'
    number:  '@buildNumber@'
    date:    '@maven.build.timestamp@'

ksul:
  archiv:
    server: http://localhost:9080/alfresco/
    binding: http://localhost:9080/alfresco/api/-default-/public/cmis/versions/1.1/atom
    user: admin
    password: admin

server:
  contextPath: /Archiv
  port: 8080

management:
  security:
    enabled: false
    info:
      git:
        mode: full

logging:
  path: ./
  level: info

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  main:
    banner-mode: log
